### ISSUE TITLE
how the hell are you going to come at me for my "bad" code??

### ISSUE THREAD

**Issue by pyp** [ryukthedev/discord-token-checker#1]
check = session.post("https://discord.com/api/v6/invite/valorant", headers=headers)

There is a reason you couldn't join roze.gg, and it's because we don't allow low-quality developers. 
What the hell are you doing? LOL, bros inviting the token to the Valorant discord server to check if it's valid. 

You really went out of your time to point the flaws in my work but your code looks like you wrote it with your toes blindfolded.

**Comment by ryukthedev** [comment]
This was made in 7 minutes for a friend, and later the updated version was updated on my github.

Thanks for your issue, I really enjoy your use of classes and using global variables inside of it.

**Comment by ryukthedev** [comment]
On a side note, you should really look into function annotation and variable annotations.

**Comment by pyp** [comment]
hop off my dick bro
